apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: saharkhiari4/student-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8089
      nodePort: 30080